# Generated by Django 4.2.4 on 2023-09-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clerk", "0003_clerk_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="patient_register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("cibil", models.CharField(max_length=100)),
                ("is_approved", models.BooleanField(default=False)),
            ],
        ),
    ]
