# Generated by Django 4.2.4 on 2023-09-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clerk", "0004_patient_register"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient_register",
            name="is_approved",
        ),
    ]
